# Generated by Django 4.1 on 2023-02-13 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auther',
            name='bname',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.books'),
        ),
        migrations.AlterField(
            model_name='auther',
            name='age',
            field=models.IntegerField(default=True),
        ),
    ]
